
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author daesm
 */
public class ToolGUI extends javax.swing.JFrame {

    // class level references
    DefaultListModel<Employee> employeeList = new DefaultListModel();
    DefaultListModel<Tool> toolList = new DefaultListModel();

    /**
     * Creates new form ToolGUI
     */
    public ToolGUI() {
        initComponents();

        //center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        pnlAddEmp = new javax.swing.JPanel();
        lblAddEmp = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmpType = new javax.swing.JLabel();
        txtEmpType = new javax.swing.JTextField();
        lblEmpID = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        btnAddEmp = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaEmployeeDetails = new javax.swing.JTextArea();
        lblEmpSummary = new javax.swing.JLabel();
        lblEmpSummary1 = new javax.swing.JLabel();
        btnResetForm = new javax.swing.JToggleButton();
        btnReviewEmployee = new javax.swing.JToggleButton();
        lblToolLoss = new javax.swing.JLabel();
        txtToolLoss = new javax.swing.JTextField();
        pnlEmployee = new javax.swing.JPanel();
        lblEmpDB = new javax.swing.JLabel();
        lblEmpList = new javax.swing.JLabel();
        lblEmpDetails = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstEmployee = new javax.swing.JList<>();
        btnLoadEmp = new javax.swing.JToggleButton();
        btnDeleteEmp = new javax.swing.JToggleButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaEmployeeInfo = new javax.swing.JTextArea();
        pnlAddTool = new javax.swing.JPanel();
        lblAddTool = new javax.swing.JLabel();
        lblToolName = new javax.swing.JLabel();
        txtToolName = new javax.swing.JTextField();
        lblToolAmt = new javax.swing.JLabel();
        txtToolAmt = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        lblAddNewTool = new javax.swing.JLabel();
        lblReviewToolDetails = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaToolDetails = new javax.swing.JTextArea();
        btnToolReview = new javax.swing.JToggleButton();
        pnlTool = new javax.swing.JPanel();
        lblTool = new javax.swing.JLabel();
        lblToolList = new javax.swing.JLabel();
        lblToolDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTools = new javax.swing.JList<>();
        btnToolLoad = new javax.swing.JButton();
        btnDeleteTool = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaToolInfo = new javax.swing.JTextArea();
        mnbMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GB Manufacturing Equipment System");

        lblAddEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAddEmp.setText("Add New Employee");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.setNextFocusableComponent(txtEmpType);

        lblEmpType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmpType.setText("Employee Type: ");

        txtEmpType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmpType.setNextFocusableComponent(txtEmpID);

        lblEmpID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmpID.setText("Employee ID: ");

        txtEmpID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmpID.setNextFocusableComponent(txtToolLoss);

        btnAddEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddEmp.setText("Add Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        txaEmployeeDetails.setColumns(20);
        txaEmployeeDetails.setRows(5);
        jScrollPane5.setViewportView(txaEmployeeDetails);

        lblEmpSummary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpSummary.setText("Employee Summary");

        lblEmpSummary1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpSummary1.setText("Enter New Employee Details: ");

        btnResetForm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResetForm.setText("Reset Form");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });

        btnReviewEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReviewEmployee.setText("Review Employee");
        btnReviewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewEmployeeActionPerformed(evt);
            }
        });

        lblToolLoss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblToolLoss.setText("Total Lost Tools: ");

        txtToolLoss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlAddEmpLayout = new javax.swing.GroupLayout(pnlAddEmp);
        pnlAddEmp.setLayout(pnlAddEmpLayout);
        pnlAddEmpLayout.setHorizontalGroup(
            pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(lblAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmpType)
                                    .addComponent(lblEmpID)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmpType, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReviewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                                .addComponent(lblToolLoss)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToolLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(lblEmpSummary1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmpSummary)
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddEmpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(btnResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
        );
        pnlAddEmpLayout.setVerticalGroup(
            pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEmp)
                .addGap(18, 18, 18)
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpSummary1)
                    .addComponent(lblEmpSummary))
                .addGap(18, 18, 18)
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddEmp)
                            .addComponent(btnReviewEmployee)))
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpType)
                            .addComponent(txtEmpType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpID)
                            .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblToolLoss)
                            .addComponent(txtToolLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnResetForm)
                .addContainerGap())
        );

        tabMain.addTab("Add Employee", pnlAddEmp);

        lblEmpDB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEmpDB.setText("Employee Database");

        lblEmpList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpList.setText("Employee List");

        lblEmpDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpDetails.setText("Employee Details");

        lstEmployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lstEmployee.setModel(employeeList);
        lstEmployee.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEmployeeValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstEmployee);

        btnLoadEmp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLoadEmp.setText("Load Employees");
        btnLoadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadEmpActionPerformed(evt);
            }
        });

        btnDeleteEmp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteEmp.setText("Delete Employee");

        txaEmployeeInfo.setColumns(20);
        txaEmployeeInfo.setRows(5);
        jScrollPane6.setViewportView(txaEmployeeInfo);

        javax.swing.GroupLayout pnlEmployeeLayout = new javax.swing.GroupLayout(pnlEmployee);
        pnlEmployee.setLayout(pnlEmployeeLayout);
        pnlEmployeeLayout.setHorizontalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmployeeLayout.createSequentialGroup()
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmployeeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEmployeeLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblEmpList, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmployeeLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmployeeLayout.createSequentialGroup()
                        .addComponent(lblEmpDetails)
                        .addGap(97, 97, 97))))
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(lblEmpDB, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnLoadEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteEmp)
                .addGap(82, 82, 82))
        );
        pnlEmployeeLayout.setVerticalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblEmpDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpList)
                    .addComponent(lblEmpDetails))
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoadEmp)
                    .addComponent(btnDeleteEmp))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        tabMain.addTab("Employee Details", pnlEmployee);

        lblAddTool.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddTool.setText("Add New Tools");

        lblToolName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblToolName.setText("Tool Name:");

        txtToolName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtToolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToolNameActionPerformed(evt);
            }
        });

        lblToolAmt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblToolAmt.setText("Tool Amount:");

        txtToolAmt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton2.setText("Add Tool");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        lblAddNewTool.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddNewTool.setText("Enter New Tool Details");

        lblReviewToolDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReviewToolDetails.setText("Review Tool Details");

        txaToolDetails.setEditable(false);
        txaToolDetails.setColumns(20);
        txaToolDetails.setRows(5);
        jScrollPane7.setViewportView(txaToolDetails);

        btnToolReview.setText("Review Tool");
        btnToolReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddToolLayout = new javax.swing.GroupLayout(pnlAddTool);
        pnlAddTool.setLayout(pnlAddToolLayout);
        pnlAddToolLayout.setHorizontalGroup(
            pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddToolLayout.createSequentialGroup()
                .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddToolLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAddNewTool, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddToolLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lblAddTool, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddToolLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblToolName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtToolName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddToolLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblToolAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtToolAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReviewToolDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddToolLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnToolReview, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        pnlAddToolLayout.setVerticalGroup(
            pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddTool)
                .addGap(21, 21, 21)
                .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddNewTool)
                    .addComponent(lblReviewToolDetails))
                .addGap(18, 18, 18)
                .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAddToolLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblToolName)
                            .addComponent(txtToolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblToolAmt)
                            .addComponent(txtToolAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlAddToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(btnToolReview))
                .addGap(62, 62, 62))
        );

        tabMain.addTab("Add Tool", pnlAddTool);

        lblTool.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTool.setText("Tool Inventory");

        lblToolList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblToolList.setText("Tool List");

        lblToolDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblToolDetails.setText("Tool Details");

        lstTools.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(lstTools);

        btnToolLoad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnToolLoad.setText("Load List");
        btnToolLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolLoadActionPerformed(evt);
            }
        });

        btnDeleteTool.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteTool.setText("Delete Tool");

        txaToolInfo.setColumns(20);
        txaToolInfo.setRows(5);
        jScrollPane3.setViewportView(txaToolInfo);

        javax.swing.GroupLayout pnlToolLayout = new javax.swing.GroupLayout(pnlTool);
        pnlTool.setLayout(pnlToolLayout);
        pnlToolLayout.setHorizontalGroup(
            pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblToolList, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblToolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(lblTool, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnToolLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteTool, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnlToolLayout.setVerticalGroup(
            pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToolList)
                    .addComponent(lblToolDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToolLoad)
                    .addComponent(btnDeleteTool))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tabMain.addTab("Tools", pnlTool);

        mnuFile.setText("File");

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnbMain.add(mnuFile);

        jMenu2.setText("Edit");
        mnbMain.add(jMenu2);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );

        tabMain.getAccessibleContext().setAccessibleName("Employee Details");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // exit the application
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void btnReviewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewEmployeeActionPerformed
        // TODO add your handling code here:

        // validate the inputs
        if (validateInputs() == false) {
            return;      // end the method if validation failed
        }
        // create the Customer object and show the information
        Employee emp = createEmployee();
        txaEmployeeDetails.setText(emp.getDetails());

    }//GEN-LAST:event_btnReviewEmployeeActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
        // Add employee details

        addEmployee();
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void lstEmployeeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEmployeeValueChanged
        // TODO add your handling code here:
        // get selected item’s index number
        int index = lstEmployee.getSelectedIndex();

        // if something was selected, show the object’s details
        if (index > -1) {
            Employee emp = employeeList.getElementAt(index);
            txaEmployeeInfo.setText(emp.getDetails());
        }

    }//GEN-LAST:event_lstEmployeeValueChanged

    private void txtToolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToolNameActionPerformed

    private void btnLoadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadEmpActionPerformed
        // TODO add your handling code here:

        loadEmployees();
    }//GEN-LAST:event_btnLoadEmpActionPerformed

    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        // TODO add your handling code here:

        reset();
    }//GEN-LAST:event_btnResetFormActionPerformed

    private void btnToolReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolReviewActionPerformed
        // TODO add your handling code here:

        // validate the inputs
        if (validateToolInputs() == false) {
            return;      // end the method if validation failed
        }

        // create the Customer object and show the information
        Tool item = createTool();
        txaToolDetails.setText(item.getToolDetails());
    }//GEN-LAST:event_btnToolReviewActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:

        addTool();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btnToolLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolLoadActionPerformed
        // TODO add your handling code here:
        
        loadTools();
    }//GEN-LAST:event_btnToolLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddEmp;
    private javax.swing.JToggleButton btnDeleteEmp;
    private javax.swing.JButton btnDeleteTool;
    private javax.swing.JToggleButton btnLoadEmp;
    private javax.swing.JToggleButton btnResetForm;
    private javax.swing.JToggleButton btnReviewEmployee;
    private javax.swing.JButton btnToolLoad;
    private javax.swing.JToggleButton btnToolReview;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblAddEmp;
    private javax.swing.JLabel lblAddNewTool;
    private javax.swing.JLabel lblAddTool;
    private javax.swing.JLabel lblEmpDB;
    private javax.swing.JLabel lblEmpDetails;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpList;
    private javax.swing.JLabel lblEmpSummary;
    private javax.swing.JLabel lblEmpSummary1;
    private javax.swing.JLabel lblEmpType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReviewToolDetails;
    private javax.swing.JLabel lblTool;
    private javax.swing.JLabel lblToolAmt;
    private javax.swing.JLabel lblToolDetails;
    private javax.swing.JLabel lblToolList;
    private javax.swing.JLabel lblToolLoss;
    private javax.swing.JLabel lblToolName;
    private javax.swing.JList<Employee> lstEmployee;
    private javax.swing.JList<String> lstTools;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JPanel pnlAddEmp;
    private javax.swing.JPanel pnlAddTool;
    private javax.swing.JPanel pnlEmployee;
    private javax.swing.JPanel pnlTool;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextArea txaEmployeeDetails;
    private javax.swing.JTextArea txaEmployeeInfo;
    private javax.swing.JTextArea txaToolDetails;
    private javax.swing.JTextArea txaToolInfo;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpType;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtToolAmt;
    private javax.swing.JTextField txtToolLoss;
    private javax.swing.JTextField txtToolName;
    // End of variables declaration//GEN-END:variables

    private void reset() {

        txtName.setText("");
        this.txtName.requestFocusInWindow();
        txtEmpType.setText("");
        txtEmpID.setText("");
        txtToolLoss.setText("");
        txaEmployeeDetails.setText("");

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void resetTool() {

        txtToolName.setText("");
        this.txtToolName.requestFocusInWindow();
        txtToolAmt.setText("");
        txaToolDetails.setText("");

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean validateInputs() {
        // get inputs from user using the textboxes
        String sName = txtName.getText();
        String sEmpType = txtEmpType.getText();
        String sEmpID = txtEmpID.getText();
        String sToolLoss = txtToolLoss.getText();

        // make sure we have a name for the order
        if (sName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter a Name",
                    "Name Error", JOptionPane.ERROR_MESSAGE);
            txtName.requestFocusInWindow();
            return false;
        }

        // make sure we have an employee type for the order
        if (sEmpType.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter an Employee Type",
                    "Employee Type Error", JOptionPane.ERROR_MESSAGE);
            txtEmpType.requestFocusInWindow();
            return false;
        }

        // make sure we have an employe ID for the order
        if (sEmpID.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter an Employee ID",
                    "Employee ID Error", JOptionPane.ERROR_MESSAGE);
            txtEmpID.requestFocusInWindow();
            return false;
        }

        // make sure we have an employe ID for the order
        if (sToolLoss.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter a Tools Lost Amount",
                    "Tool Loss Error", JOptionPane.ERROR_MESSAGE);
            txtToolLoss.requestFocusInWindow();
            return false;

        }

        // all is good so return true
        return true;

        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean validateToolInputs() {
        // get inputs from user using the textboxes
        String stoolNm = txtToolName.getText();
        String sToolAmt = txtToolAmt.getText();

        // make sure we have a name for the tool
        if (stoolNm.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter a Tool Name",
                    "Name Error", JOptionPane.ERROR_MESSAGE);
            txtToolName.requestFocusInWindow();
            return false;
        }

        // make sure we have an amount for the tool
        if (sToolAmt.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter an Amount",
                    "Amount Error", JOptionPane.ERROR_MESSAGE);
            txtToolAmt.requestFocusInWindow();
            return false;
        }

        // check to see if the amount is a valid number
        try {
            Double.parseDouble(sToolAmt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Amount must be a number",
                    "Amount Error", JOptionPane.ERROR_MESSAGE);
            txtToolAmt.setText("");
            txtToolAmt.requestFocusInWindow();
            return false;
        }

        if (Double.parseDouble(sToolAmt) <= 0) {
            JOptionPane.showMessageDialog(this, "Amount must be greater than 0",
                    "Amount Error", JOptionPane.ERROR_MESSAGE);
            txtToolAmt.setText("");
            txtToolAmt.requestFocusInWindow();
            return false;
        }

        // all is good so return true
        return true;

    }

    private Employee createEmployee() {
        String empName = txtName.getText();
        String empType = txtEmpType.getText();
        int empID = Integer.parseInt(txtEmpID.getText());
        int toolLoss = Integer.parseInt(txtToolLoss.getText());

        Employee emp = new Employee(empName, empType, empID, toolLoss);
        return emp;

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void addEmployee() {
        if (validateInputs() == false) {
            return;    // end the method if validation failed
        }

        Employee emp = createEmployee();
        employeeList.addElement(emp);
        txaEmployeeDetails.setText(emp.getDetails());

        try {
            DataIO data = new DataIO(); // create DataIO object
            data.add(emp);
            loadEmployees(); // load all employees

            // reset for the next employee
            reset();

            //move to the client orders tab
            tabMain.setSelectedIndex(1);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "File IO Error", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Not Found Error: " + ex.getMessage(),
                    "Database Driver Error", JOptionPane.ERROR_MESSAGE);
        }

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadEmployees() {

        try {
            DataIO data = new DataIO(); // create DataIO object
            ArrayList<Employee> employees = data.getList();

            // clear out the DefaultListModel and textarea
            employeeList.clear();
            txaEmployeeDetails.setText("");

            // copy each object from the ArrayList over to the DefaultListModel
            for (int i = 0; i < employees.size(); i++) {
                employeeList.addElement(employees.get(i));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Tool createTool() {

        String toolNm = txtToolName.getText();
        double amt = Double.parseDouble(txtToolAmt.getText());

        Tool tooldb = new Tool(0, toolNm, amt);
        return tooldb;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void addTool() {
        if (validateToolInputs() == false) {
            return;    // end the method if validation failed
        }

        Tool item = createTool();
        toolList.addElement(item);
        txaToolDetails.setText(item.getToolDetails());

        try {
            ToolDataIO data = new ToolDataIO(); // create DataIO object
            data.add(item);
            loadTools(); // load all tools

            // reset for the next tool
            resetTool();

            //move to the client orders tab
            tabMain.setSelectedIndex(2);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "File IO Error", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Not Found Error: " + ex.getMessage(),
                    "Database Driver Error", JOptionPane.ERROR_MESSAGE);
        }

        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadTools() {
        
        try {
            ToolDataIO data = new ToolDataIO(); // create DataIO object
            ArrayList<Tool> tools = data.getList();

            // clear out the DefaultListModel and textarea
            toolList.clear();
            txaToolDetails.setText("");

            // copy each object from the ArrayList over to the DefaultListModel
            for (int i = 0; i < tools.size(); i++) {
                toolList.addElement(tools.get(i));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
